# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IlliniDrainageTools
                                 A QGIS plugin
 Performs Specific Draiange Related Tasks and Analysis on a Site
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-15
        copyright            : (C) 2022 by FALASY  Anamelechi
        email                : fvw.services@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Anamelechi FALASY & Richard COOKE'
__date__ = '2022-03-15'
__copyright__ = '(C) 2022 by Anamelechi FALASY & Richard COOKE'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IlliniDrainageTools class from file IlliniDrainageTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .illini_drainage_tools import IlliniDrainageToolsPlugin
    return IlliniDrainageToolsPlugin(iface)
